In [3]:
import gensim
from gensim.models import word2vec, KeyedVectors

In [4]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [5]:
## Load the Dataset
import pandas as pd
data = pd.read_csv("all_kindle_review .csv")
data.head()

Unnamed: 0.1  Unnamed: 0        asin  helpful  rating  \
0             0       11539  B0033UV8HI  [8, 10]       3   
1             1        5957  B002HJV4DE   [1, 1]       5   
2             2        9146  B002ZG96I4   [0, 0]       3   
3             3        7038  B002QHWOEU   [1, 3]       3   
4             4        1776  B001A06VJ8   [0, 1]       4   

                                          reviewText   reviewTime  \
0  Jace Rankin may be short, but he's nothing to ...   09 2, 2010   
1  Great short read.  I didn't want to put it dow...   10 8, 2013   
2  I'll start by saying this is the first of four...  04 11, 2014   
3  Aggie is Angela Lansbury who carries pocketboo...   07 5, 2014   
4  I did not expect this type of book to be in li...  12 31, 2012   

       reviewerID  reviewerName                   summary  unixReviewTime  
0  A3HHXRELK8BHQG        Ridley  Entertaining But Average      1283385600  
1  A2RGNZ0TRF578I  Holly Butler   Terrific menage scenes!      1381190400  
2  A3S0H2HV6U1I7F       Merissa          Snapdragon Alley      1397174400  
3   AC4OQW3GZ919J    Cleargrace    very light murder cozy      1404518400  
4  A3C9V987IQHOQD      Rjostler                      Book      1356912000

In [6]:
df = data[['reviewText', 'rating']]
df.head()

reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [7]:
## Positive review is 1 and negative review is 0
df['rating'] = df['rating'].apply(lambda x: 0 if x<3 else 1)

C:\Users\Manish\AppData\Local\Temp\ipykernel_2312\915096891.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rating'] = df['rating'].apply(lambda x: 0 if x<3 else 1)


In [8]:
import re
from nltk.corpus import stopwords
from bs4 import BeautifulSoup

In [9]:
## Removing special characters
df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', '', x))
## Remove the stopwords
df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', str(x)))
## Remove html tags
df['reviewText'] = df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any addtional spaces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\Manish\AppData\Local\Temp\ipykernel_2312\2732512082.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9]+', '', x))
C:\Users\Manish\AppData\Local\Temp\ipykernel_2312\2732512082.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
C:\Users\Manish\AppData\Local\Temp\ipykernel_2312\2732512082.py:6: SettingWit

In [10]:
import re
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [11]:
corpus = []
for i in range(0, len(df)):
    review = df['reviewText'][i].split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [12]:
corpus

['Jace Rankin may short he nothing mess man hauled saloon undertaker know Hes famous bounty hunter Oregon 1890s shot man saloon finished year long quest avenge sister murder trying figure next When snottynosed farm boy rescued gang bully offer money kill man forced ranch reluctantly agrees bring man justice kill outright But first need tell sister widower newsKyla Kyle Springer Bailey riding trail sleeping ground past month trying find Jace She want revenge man killed husband took ranch amongst crime shes keen detour Jace want take But realizes shes option hide behind boy persona best try keep pace When confrontation along way get shot Jace discovers Kyles Kyla come clean whole reason need scoundrel dead hope hell still help herThe book share touching moment slowblooming romance Kyla find good reason fear men hide behind boy persona Watching Jace slowly pull shell help conquer fear endearing Her pain real deeplyrooted didnt disappear face sexiness Neither understandable aversion marria

In [13]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [15]:
words

[['jace',
  'rankin',
  'may',
  'short',
  'he',
  'nothing',
  'mess',
  'man',
  'hauled',
  'saloon',
  'undertaker',
  'know',
  'hes',
  'famous',
  'bounty',
  'hunter',
  'oregon',
  'shot',
  'man',
  'saloon',
  'finished',
  'year',
  'long',
  'quest',
  'avenge',
  'sister',
  'murder',
  'trying',
  'figure',
  'next',
  'when',
  'snottynosed',
  'farm',
  'boy',
  'rescued',
  'gang',
  'bully',
  'offer',
  'money',
  'kill',
  'man',
  'forced',
  'ranch',
  'reluctantly',
  'agrees',
  'bring',
  'man',
  'justice',
  'kill',
  'outright',
  'but',
  'first',
  'need',
  'tell',
  'sister',
  'widower',
  'newskyla',
  'kyle',
  'springer',
  'bailey',
  'riding',
  'trail',
  'sleeping',
  'ground',
  'past',
  'month',
  'trying',
  'find',
  'jace',
  'she',
  'want',
  'revenge',
  'man',
  'killed',
  'husband',
  'took',
  'ranch',
  'amongst',
  'crime',
  'shes',
  'keen',
  'detour',
  'jace',
  'want',
  'take',
  'but',
  'realizes',
  'shes',
  'option',


In [16]:
import gensim

In [17]:
## Lets train Word2vec from scratch
model = gensim.models.Word2Vec(sentences=words, vector_size=100, window=5)

In [18]:
## To get all the vocabulary
model.wv.index_to_key

['book',
 'story',
 'read',
 'the',
 'one',
 'character',
 'like',
 'good',
 'this',
 'would',
 'really',
 'love',
 'it',
 'get',
 'time',
 'author',
 'reading',
 'series',
 'much',
 'first',
 'well',
 'even',
 'didnt',
 'short',
 'know',
 'way',
 'could',
 'great',
 'make',
 'sex',
 'little',
 'dont',
 'want',
 'two',
 'thing',
 'think',
 'he',
 'find',
 'plot',
 'also',
 'romance',
 'end',
 'there',
 'life',
 'im',
 'see',
 'enjoyed',
 'go',
 'scene',
 'never',
 'take',
 'many',
 'woman',
 'written',
 'but',
 'kindle',
 'say',
 'she',
 'work',
 'and',
 'thought',
 'lot',
 'bit',
 'found',
 'going',
 'give',
 'interesting',
 'year',
 'liked',
 'writing',
 'loved',
 'novel',
 'another',
 'better',
 'feel',
 'got',
 'come',
 'hot',
 'still',
 'if',
 'man',
 'enough',
 'back',
 'though',
 'people',
 'made',
 'something',
 'part',
 'cant',
 'friend',
 'reader',
 'review',
 'star',
 'page',
 'bad',
 'need',
 'new',
 'wasnt',
 'keep',
 'free',
 'doesnt',
 'world',
 'its',
 'relationship',
 

In [19]:
model.corpus_count

12000

In [20]:
model.epochs

5

In [21]:
import numpy as np
def avg_word2vec(doc):
    vecs = [model.wv[word] for word in doc if word in model.wv]
    if len(vecs) > 0:
        return np.mean(vecs, axis=0)
    else:
        return np.zeros(model.vector_size)

In [22]:
from tqdm import tqdm

In [23]:
## Apply for entire sentences
X = [avg_word2vec(doc) for doc in tqdm(words)]

100%|██████████| 12000/12000 [00:01<00:00, 9098.38it/s]


In [24]:
X

[array([-0.04120809,  0.22776684, -0.04397476, -0.12693927, -0.2345543 ,
        -0.69175255,  0.11746154,  0.50238186, -0.33220863, -0.1507583 ,
        -0.19791843, -0.3585741 , -0.17906973,  0.19444738, -0.17021817,
        -0.11668327,  0.10952938, -0.09782363, -0.13633797, -0.5847958 ,
         0.11894792,  0.03036877,  0.03886145, -0.07719981, -0.01581367,
         0.06616575, -0.25342673, -0.2305703 , -0.18795948, -0.00626687,
         0.25630963,  0.13740984,  0.117433  , -0.388784  , -0.02285245,
         0.33902833,  0.12050448, -0.4421662 , -0.2569229 , -0.5707973 ,
        -0.09961357, -0.41792235,  0.0995319 , -0.06947157,  0.32263422,
        -0.24551962, -0.1928016 , -0.171614  ,  0.21776949,  0.07652737,
         0.09941373, -0.28197414, -0.05078249, -0.07161485, -0.1880588 ,
         0.1515469 ,  0.23581786, -0.03538515, -0.39096516,  0.03263135,
         0.16484143,  0.06528714, -0.08554043,  0.08134409, -0.43284917,
         0.39924252,  0.16245663,  0.11016703, -0.4

In [25]:
X_new = np.array(X)

In [26]:
X_new.shape

(12000, 100)

In [27]:
X_new[0].shape

(100,)

In [28]:
y = df['rating'].values

In [29]:
y

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [30]:
df.shape, X_new.shape, y.shape

((12000, 2), (12000, 100), (12000,))

In [31]:
## this is final independent feature
df_new = pd.DataFrame(np.vstack(X))
dfs = []
for i in range(len(X)):
    dfs.append(pd.DataFrame(X[i].reshape(1, -1)))
df_new = pd.concat(dfs, ignore_index=True)

In [32]:
df_new.shape

(12000, 100)

In [33]:
df_new.head()

0         1         2         3         4         5         6   \
0 -0.041208  0.227767 -0.043975 -0.126939 -0.234554 -0.691753  0.117462   
1  0.001277  0.374052  0.019560 -0.002201  0.160873 -0.646923  0.021086   
2 -0.123564  0.271757  0.118208 -0.000980  0.008812 -0.577785  0.131580   
3 -0.235443  0.345481  0.133686  0.041558  0.203993 -0.485292  0.218734   
4  0.003236  0.370509  0.174328  0.137052  0.118966 -0.311591 -0.051275   

         7         8         9   ...        90        91        92        93  \
0  0.502382 -0.332209 -0.150758  ...  0.214111  0.155939 -0.043289  0.134299   
1  0.736819 -0.578762 -0.570586  ...  0.547701  0.158358 -0.074271  0.280142   
2  0.680843 -0.407645 -0.470274  ...  0.382970  0.208068 -0.020778  0.193646   
3  0.751801 -0.398928 -0.439656  ...  0.516352  0.305769 -0.032865  0.096013   
4  0.720342 -0.187861 -0.671061  ...  0.445704  0.218068  0.365968 -0.041025   

         94        95        96        97        98        99  
0  0.364173 -0.027401  0.114735 -0.260245  0.125201 -0.088891  
1  0.416864  0.261038  0.363854 -0.168208  0.140752 -0.541459  
2  0.480714  0.220662  0.189474 -0.260198  0.086873 -0.231090  
3  0.437834  0.466932  0.314362 -0.428197 -0.082353 -0.299489  
4  0.476254  0.284760  0.245166 -0.188742  0.179625 -0.203945  

[5 rows x 100 columns]

In [34]:
## Independent feature
X = df_new

In [35]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [36]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [37]:
X_train.head()

0         1         2         3         4         5         6   \
5998  -0.112225  0.272858  0.001746 -0.015575 -0.052984 -0.563408  0.081222   
9147  -0.260493  0.362817  0.131596  0.146328  0.197528 -0.534821  0.011827   
5713   0.006614  0.432860  0.186384  0.043053  0.383297 -0.407068  0.021563   
5446  -0.071580  0.305186  0.037965  0.135280  0.206710 -0.389307  0.175968   
11671 -0.061788  0.294667  0.120207  0.056948  0.014422 -0.509049  0.157281   

             7         8         9   ...        90        91        92  \
5998   0.676894 -0.359205 -0.394257  ...  0.438531  0.158269  0.068363   
9147   0.613483 -0.213875 -0.526918  ...  0.427397  0.280245 -0.009030   
5713   0.869986 -0.406848 -0.855596  ...  0.833558  0.201341  0.283597   
5446   0.697538 -0.487295 -0.476177  ...  0.538056  0.275262 -0.134964   
11671  0.659444 -0.361811 -0.398216  ...  0.549709  0.162083  0.204141   

             93        94        95        96        97        98        99  
5998   0.133900  0.357427  0.196550  0.241965 -0.331639  0.074393 -0.248517  
9147   0.007074  0.309864  0.338276  0.447715 -0.298152 -0.156972 -0.211897  
5713  -0.029482  0.489354  0.774441  0.452123 -0.227597  0.029448 -0.541902  
5446   0.154803  0.502280  0.359584  0.298684 -0.252081  0.127170 -0.568992  
11671  0.140775  0.428010  0.186109  0.112334 -0.171843  0.112469 -0.198928  

[5 rows x 100 columns]

In [38]:
y_train

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [39]:
from sklearn.naive_bayes import GaussianNB
nb_model_avgword2vec = GaussianNB().fit(X_train, y_train)

In [40]:
y_pred = nb_model_avgword2vec.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [42]:
print(accuracy_score(y_test, y_pred))

0.70875


In [43]:
confusion_matrix(y_test, y_pred)

array([[ 559,  222],
       [ 477, 1142]], dtype=int64)

In [44]:
def predict_review_sentiment(review_text):
    # Lowercase
    review_text = review_text.lower()
    
    # Remove special characters
    review_text = re.sub('[^a-z A-Z 0-9]+', '', review_text)
    
    # Remove stopwords
    review_text = " ".join([word for word in review_text.split() if word not in stopwords.words('english')])
    
    # Remove URL
    review_text = re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', review_text)
    
    # Remove HTML
    review_text = BeautifulSoup(review_text, 'lxml').get_text()
    
    # Lemmatize
    lemmatized = [lemmatizer.lemmatize(word) for word in review_text.split()]
    
    # Convert to word2vec vector
    vec = avg_word2vec(lemmatized).reshape(1, -1)
    
    # Predict
    prediction = nb_model_avgword2vec.predict(vec)
    
    if prediction[0] == 1:
        return "Positive Review ✅"
    else:
        return "Negative Review ❌"


In [57]:
test_review = "One of the best books I've read this year. Beautifully written."
print(predict_review_sentiment(test_review))


Positive Review ✅
