In [33]:
## BOW, TF-IDF, Machine Learning Algorithms
import pandas as pd
messages = pd.read_csv('SpamCollectionSMS.txt',header=None,sep="\t", names=['label', 'message'])

In [34]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [35]:
## data cleaning and preprocessing
import re
import nltk

In [36]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords
ps = PorterStemmer()

In [37]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

## Create Bag of Words

In [38]:
## Output features
y = pd.get_dummies(messages['label']).astype(int)

In [39]:
y

ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [40]:
y = y.iloc[:,0].values

In [41]:
y

array([1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..., 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

In [42]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

In [43]:
## Create Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))

In [44]:
X_train

['mag meet avo point',
 'done',
 'went project centr',
 'come sec somebodi want see',
 'gonna go get taco',
 'aiyar u poor thing give u support k jia think u',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'could seen recognis face',
 'need th campu atm could pick hour two',
 'erm woodland avenu somewher get parish magazin telephon number',
 'po de need job aha',
 'tomarrow want got court lt decim gt come bu stand',
 'congratul thank good friend u xma prize claim easi call p per minut bt nation rate',
 'go sao mu today done',
 'still west coast haiz take forev come back',
 'realli master',
 'dear good morn',
 'good wonder wont say hi smile cope long distanc',
 'cant pick phone right pl send messag',
 'ok prob',
 'back lemm know readi',
 'ok anybodi ask abt u tel p',
 'way',
 'call ok said call',
 'reassur crazi world',
 'winner special select receiv cash award speak live oper claim call pm cost p',
 'test earlier appre

In [45]:
## Independent features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [46]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float = lambda x: "%.3g" % x))


In [47]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [48]:
cv.vocabulary_

{'meet': 1269,
 'point': 1594,
 'done': 547,
 'went': 2384,
 'project': 1647,
 'centr': 308,
 'come': 381,
 'sec': 1808,
 'somebodi': 1918,
 'want': 2331,
 'see': 1814,
 'gonna': 819,
 'go': 797,
 'get': 768,
 'go get': 802,
 'poor': 1600,
 'thing': 2100,
 'give': 789,
 'support': 2028,
 'think': 2101,
 'urgent': 2268,
 'ur': 2247,
 'award': 117,
 'complimentari': 395,
 'trip': 2181,
 'entri': 615,
 'claim': 342,
 'txt': 2199,
 'di': 518,
 'ls': 1210,
 'ur award': 2248,
 'could': 432,
 'seen': 1822,
 'face': 650,
 'need': 1394,
 'th': 2089,
 'campu': 278,
 'atm': 104,
 'pick': 1552,
 'hour': 967,
 'two': 2198,
 'somewher': 1925,
 'number': 1444,
 'po': 1587,
 'de': 491,
 'job': 1044,
 'aha': 33,
 'got': 835,
 'lt': 1211,
 'decim': 499,
 'gt': 857,
 'bu': 223,
 'stand': 1961,
 'lt decim': 1212,
 'decim gt': 500,
 'congratul': 403,
 'thank': 2091,
 'good': 821,
 'friend': 734,
 'xma': 2464,
 'prize': 1635,
 'easi': 585,
 'call': 241,
 'per': 1534,
 'minut': 1301,
 'bt': 217,
 'nation': 1

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [51]:
spam_detect_model

MultinomialNB()

In [52]:
y_pred = spam_detect_model.predict(X_test)

In [53]:
from sklearn.metrics import accuracy_score, classification_report

In [54]:
accuracy_score(y_test, y_pred)

0.9838565022421525

In [55]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.90      0.94       151
           1       0.98      1.00      0.99       964

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



## Create TF-IDF Model

In [57]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [59]:
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [60]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.232, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 

In [61]:
tv.vocabulary_

{'press': 1645,
 'da': 474,
 'network': 1416,
 'support': 2036,
 'free': 722,
 'messag': 1295,
 'activ': 14,
 'text': 2081,
 'repli': 1738,
 'word': 2426,
 'term': 2078,
 'condit': 401,
 'visit': 2293,
 'www': 2451,
 'com': 380,
 'free messag': 729,
 'free text': 736,
 'term condit': 2079,
 'visit www': 2294,
 'well': 2373,
 'done': 548,
 'costa': 433,
 'del': 510,
 'sol': 1930,
 'holiday': 952,
 'await': 119,
 'collect': 373,
 'call': 240,
 'toclaim': 2140,
 'sae': 1784,
 'tc': 2060,
 'pobox': 1614,
 'stockport': 1992,
 'sk': 1904,
 'xh': 2461,
 'cost': 430,
 'pm': 1609,
 'max': 1272,
 'min': 1303,
 'well done': 2374,
 'costa del': 434,
 'del sol': 511,
 'sol holiday': 1931,
 'holiday await': 953,
 'await collect': 120,
 'collect call': 374,
 'call toclaim': 265,
 'toclaim sae': 2141,
 'sae tc': 1786,
 'tc pobox': 2061,
 'pobox stockport': 1615,
 'stockport sk': 1993,
 'sk xh': 1906,
 'xh cost': 2462,
 'cost pm': 431,
 'pm max': 1611,
 'max min': 1273,
 'problem': 1663,
 'right': 1758

In [62]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB().fit(X_train, y_train)

In [63]:
## predictions
y_pred = spam_tfidf_model.predict(X_test)

In [64]:
score = accuracy_score(y_test, y_pred)
print(score)

0.9730941704035875


In [65]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.81      0.89       148
           1       0.97      1.00      0.98       967

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.94      1115
weighted avg       0.97      0.97      0.97      1115

