In [1]:
import gensim
from gensim.models import word2vec, KeyedVectors

In [2]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [3]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [4]:
import pandas as pd
messages = pd.read_csv('SpamCollectionSMS.txt',header=None,sep="\t", names=['label', 'message'])

In [5]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [6]:
import re
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [7]:
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [8]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [9]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [10]:
words = []
for sent in corpus:
    sent_token = sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

In [11]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [12]:
import gensim

In [13]:
## Lets train Word2vec from scratch
model = gensim.models.Word2Vec(sentences=words, vector_size=100, window=5)

In [14]:
## To get all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'time',
 'good',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'text',
 'love',
 'only',
 'want',
 'send',
 'need',
 'one',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'our',
 'dont',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'her',
 'any',
 'pls',
 'ha',
 'co',
 'did',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'clai

In [15]:
model.corpus_count

5569

In [16]:
model.epochs

5

In [17]:
model.wv.similar_by_word('good')

[('morning', 0.9989833831787109),
 ('day', 0.9989262223243713),
 ('my', 0.9988833665847778),
 ('well', 0.9988728165626526),
 ('hope', 0.9988033771514893),
 ('happy', 0.9987916350364685),
 ('dear', 0.9987303018569946),
 ('wish', 0.9987260103225708),
 ('boy', 0.9987219572067261),
 ('all', 0.9986736178398132)]

In [18]:
model.wv['good'].shape

(100,)

In [19]:
import numpy as np
def avg_word2vec(doc):
    vecs = [model.wv[word] for word in doc if word in model.wv]
    if len(vecs) > 0:
        return np.mean(vecs, axis=0)
    else:
        return np.zeros(model.vector_size)

In [20]:
from tqdm import tqdm

In [21]:
## Apply for entire sentences
X = [avg_word2vec(doc) for doc in tqdm(words)]

100%|██████████| 5569/5569 [00:00<00:00, 25131.75it/s]


In [22]:
X

[array([-0.16788824,  0.2465539 ,  0.13881554,  0.14235245,  0.11600549,
        -0.46664476,  0.26625675,  0.5554432 , -0.2606669 , -0.18071157,
        -0.13978085, -0.40040916,  0.02821419,  0.10069186,  0.20047428,
        -0.21959981,  0.11351574, -0.336156  , -0.04288166, -0.5562665 ,
         0.18461902,  0.21326765,  0.19874398, -0.16968411, -0.07936684,
         0.08648089, -0.26318833, -0.22972187, -0.23143603,  0.03917783,
         0.32441747, -0.06776025,  0.11424696, -0.19184351, -0.07799653,
         0.29248878,  0.05043757, -0.10454898, -0.07432392, -0.41512868,
         0.06956666, -0.22282647, -0.15867923,  0.0454096 ,  0.16369306,
        -0.07456728, -0.16838557, -0.09402797,  0.16980667,  0.19940026,
         0.15846187, -0.30195364, -0.1073662 , -0.02925765, -0.14409852,
         0.15683785,  0.1697843 ,  0.05466848, -0.3333505 ,  0.1027391 ,
        -0.07201049,  0.07476781, -0.04550757, -0.02972693, -0.34146872,
         0.34717125,  0.12752394,  0.09583334, -0.2

In [23]:
X_new = np.array(X)

In [24]:
X_new.shape

(5569, 100)

In [25]:
X_new[0]

array([-0.16788824,  0.2465539 ,  0.13881554,  0.14235245,  0.11600549,
       -0.46664476,  0.26625675,  0.55544323, -0.26066691, -0.18071157,
       -0.13978085, -0.40040916,  0.02821419,  0.10069186,  0.20047428,
       -0.21959981,  0.11351574, -0.33615601, -0.04288166, -0.55626649,
        0.18461902,  0.21326765,  0.19874398, -0.16968411, -0.07936684,
        0.08648089, -0.26318833, -0.22972187, -0.23143603,  0.03917783,
        0.32441747, -0.06776025,  0.11424696, -0.19184351, -0.07799653,
        0.29248878,  0.05043757, -0.10454898, -0.07432392, -0.41512868,
        0.06956666, -0.22282647, -0.15867923,  0.0454096 ,  0.16369306,
       -0.07456728, -0.16838557, -0.09402797,  0.16980667,  0.19940026,
        0.15846187, -0.30195364, -0.1073662 , -0.02925765, -0.14409852,
        0.15683785,  0.16978429,  0.05466848, -0.33335051,  0.1027391 ,
       -0.07201049,  0.07476781, -0.04550757, -0.02972693, -0.34146872,
        0.34717125,  0.12752394,  0.09583334, -0.24758895,  0.23

In [26]:
X_new[0].shape

(100,)

In [27]:
## Dependent features
## Output features
y = pd.get_dummies(messages['label']).astype(int)
y = y.iloc[:,0].values

In [28]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [29]:
messages.shape, X_new.shape, y.shape

((5572, 2), (5569, 100), (5572,))

In [33]:
## Dependent features
## Output features
y = messages[list(map(lambda x: len(x)>0, corpus))]
y = pd.get_dummies(y['label']).astype(int)
y = y.iloc[:,0].values

In [34]:
y.shape

(5569,)

In [37]:
## this is final independent feature
df = pd.DataFrame(np.vstack(X))
dfs = []
for i in range(len(X)):
    dfs.append(pd.DataFrame(X[i].reshape(1, -1)))
df = pd.concat(dfs, ignore_index=True)

In [38]:
df.shape

(5569, 100)

In [39]:
df.head()

0         1         2         3         4         5         6   \
0 -0.167888  0.246554  0.138816  0.142352  0.116005 -0.466645  0.266257   
1 -0.153383  0.211313  0.113079  0.120566  0.105260 -0.414467  0.229217   
2 -0.173147  0.239863  0.159283  0.197310  0.130519 -0.500280  0.275544   
3 -0.224527  0.336725  0.176122  0.177220  0.151253 -0.626674  0.351998   
4 -0.201281  0.280086  0.158714  0.154259  0.137025 -0.537376  0.302028   

         7         8         9   ...        90        91        92        93  \
0  0.555443 -0.260667 -0.180712  ...  0.384142  0.181426 -0.045030  0.160756   
1  0.479795 -0.226626 -0.146987  ...  0.333242  0.145324 -0.042328  0.140031   
2  0.583813 -0.283301 -0.192192  ...  0.375637  0.210344 -0.058006  0.205594   
3  0.735345 -0.352732 -0.233973  ...  0.518173  0.227963 -0.066728  0.209858   
4  0.634233 -0.300125 -0.209414  ...  0.449742  0.188994 -0.052467  0.179576   

         94        95        96        97        98        99  
0  0.468930  0.212730  0.158838 -0.201873  0.168605 -0.090761  
1  0.398429  0.175372  0.129575 -0.181200  0.141724 -0.080836  
2  0.480886  0.219848  0.105738 -0.214399  0.155031 -0.075864  
3  0.616089  0.278529  0.224011 -0.272735  0.224211 -0.118755  
4  0.529923  0.242530  0.189901 -0.244094  0.191237 -0.102014  

[5 rows x 100 columns]

In [40]:
## Independent feature
X = df

In [47]:
X.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
95    0
96    0
97    0
98    0
99    0
Length: 100, dtype: int64

In [41]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [43]:
X_train.head()

0         1         2         3         4         5         6   \
1    -0.153383  0.211313  0.113079  0.120566  0.105260 -0.414467  0.229217   
1052 -0.180446  0.267118  0.148879  0.150208  0.126604 -0.490334  0.278611   
2349 -0.242946  0.337566  0.196658  0.175417  0.161025 -0.606165  0.344934   
375  -0.220893  0.320019  0.177292  0.173613  0.148222 -0.581072  0.331893   
2531 -0.223547  0.331888  0.179259  0.174097  0.157843 -0.629559  0.357288   

            7         8         9   ...        90        91        92  \
1     0.479795 -0.226626 -0.146987  ...  0.333242  0.145324 -0.042328   
1052  0.590663 -0.274084 -0.190162  ...  0.406306  0.191787 -0.049216   
2349  0.733051 -0.338439 -0.249721  ...  0.518192  0.227880 -0.066487   
375   0.705249 -0.328610 -0.227997  ...  0.491662  0.227231 -0.056396   
2531  0.747410 -0.345893 -0.234410  ...  0.523189  0.233529 -0.064740   

            93        94        95        96        97        98        99  
1     0.140031  0.398429  0.175372  0.129575 -0.181200  0.141724 -0.080836  
1052  0.171835  0.491967  0.229056  0.171388 -0.206964  0.177224 -0.102863  
2349  0.204807  0.604588  0.297222  0.227629 -0.277232  0.229104 -0.121668  
375   0.196512  0.592665  0.276229  0.212192 -0.248821  0.216346 -0.120749  
2531  0.205631  0.632043  0.284157  0.224790 -0.261901  0.225344 -0.140643  

[5 rows x 100 columns]

In [44]:
y_train

array([1, 1, 1, ..., 0, 1, 1])

In [45]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [46]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [48]:
y_pred = classifier.predict(X_test)

In [49]:
from sklearn.metrics import accuracy_score, classification_report

In [51]:
print(accuracy_score(y_test, y_pred))

0.966786355475763


In [53]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.84      0.87       148
           1       0.98      0.99      0.98       966

    accuracy                           0.97      1114
   macro avg       0.94      0.92      0.93      1114
weighted avg       0.97      0.97      0.97      1114



In [54]:
import gensim.downloader as api
print(api.BASE_DIR)

C:\Users\Manish/gensim-data
