In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## sentences
sent = [
    'the glass of milk',
    'the cup of tea',
    'the glass of juice',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [ ]:
sent

['the glass of milk',
 'the cup of tea',
 'the glass of juice',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size = 10000

In [6]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size) for words in sent]
one_hot_repr

[[1855, 6887, 4898, 4953],
 [1855, 7582, 4898, 2279],
 [1855, 6887, 4898, 8604],
 [5233, 1330, 7417, 836, 7214],
 [5233, 1330, 7417, 836, 1303],
 [8928, 1855, 8895, 4898, 3136],
 [7997, 6414, 654, 836]]

In [7]:
## word Embedding Representaton
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1855 6887 4898 4953]
 [   0    0    0    0 1855 7582 4898 2279]
 [   0    0    0    0 1855 6887 4898 8604]
 [   0    0    0 5233 1330 7417  836 7214]
 [   0    0    0 5233 1330 7417  836 1303]
 [   0    0    0 8928 1855 8895 4898 3136]
 [   0    0    0    0 7997 6414  654  836]]


In [10]:
## feature representation
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')
model.build(input_shape=(None, sent_length))


c:\Users\Saksham-Singh\anaconda3\envs\code_venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step


array([[[ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [-0.02640563, -0.01762372, -0.0256893 , -0.03554133,
         -0.03752066,  0.01414024,  0.00805396, -0.01018622,
          0.03108975,  0.02979847],
        [-0.00290972,  0.00187609,  0.01507348,  0.00406992,
         -0.02100638,  0.01235409, -0.013288  ,  0.00184686,
         -0.00250559,  0.01073201],
        [ 0.04645271,  0.01247977,  0.03488343, -0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 1855, 6887, 4898, 4953], dtype=int32)

In [20]:
model.predict(embedded_docs[0].reshape(1, -1))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


array([[[ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [ 0.04649988, -0.00172802, -0.02009839,  0.01526347,
         -0.03830304,  0.00517987, -0.00868278,  0.04951024,
         -0.0155145 , -0.04442853],
        [-0.02640563, -0.01762372, -0.0256893 , -0.03554133,
         -0.03752066,  0.01414024,  0.00805396, -0.01018622,
          0.03108975,  0.02979847],
        [-0.00290972,  0.00187609,  0.01507348,  0.00406992,
         -0.02100638,  0.01235409, -0.013288  ,  0.00184686,
         -0.00250559,  0.01073201],
        [ 0.04645271,  0.01247977,  0.03488343, -0.0